.PHONY: html
html:
	jupyter nbconvert --to html 'ExampleAromaAnalysis.ipynb'
	jupyter nbconvert --to html 'RefactorFrequencyFeature.ipynb'
	jupyter nbconvert --to html 'RefactorNiftiHeaders.ipynb'
	jupyter nbconvert --to html 'RefactorRegFilt.ipynb'
	jupyter nbconvert --to html 'RefactorSpatialFeature.ipynb'
	jupyter nbconvert --to html 'RefactorTimeSeriesFeature.ipynb'

clean:
	rm -f *.html *.nii.gz
